# Generated by Django 4.1.1 on 2023-05-09 12:53

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('madini', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='madini',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
