# Generated by Django 4.1.1 on 2023-05-09 12:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madini', '0002_alter_madini_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='madini',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
