# Generated by Django 4.1.1 on 2023-05-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madini', '0004_alter_madini_options_madini_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='madini',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
